version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "8080:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    nodeapp1:
        image: node_eat
        environment:
            - PORT=1111
    nodeapp2:
        image: node_eat
        environment:
            - PORT=2222
    nodeapp3:
        image: node_eat
        environment:
            - PORT=3333
    nodeapp4:
        image: node_eat
        environment:
            - PORT=4444
        